### ISSUE TITLE
TouchUpInside action issue

### ISSUE THREAD

**Issue by skuske** [HappyIosDeveloper/TouchableView#1]
Even if I move the finger outside the view, the 'TouchUpInside' action is still triggered. Why is that and how can I fix that? If the finger is moved outside the view, the action should actually not be executed.

Thanks! :o)

**Comment by HappyIosDeveloper** [comment]
Hey! 
Thanks for the comment but the demo project is working fine 🤔

**Comment by skuske** [comment]
Hmmm, I am using this in an ObjC project, and it works just fine, except for the fact that TouchUpInside does not work as expected. As mentioned above, it still triggers if the touch ends outside the view.

**Comment by skuske** [comment]
Sorry, my mistake. Wrong declaration. Got it working now.
